import quiz1img from './images/quiz1img.jpeg';
import quiz2img from './images/quiz2img.jpg';

export const quizcontent = [
  {
    key: '01',
    imagesrc: quiz1img,
    genKnowledge: "What side of the body is this bone from?",
    genAnswer: "genAnswer",
    intKnowledge: "This bone forms from the fusion of which 3 bones?",
    intAnswer: "intAnswer",
    advKnowledge: "Fusion of these 3 bones generally occurs between what ages?",
    advAnswer: "intAnswer",
    enable: true
  },
  {
    key: '02',
    imagesrc: quiz2img,
    genKnowledge: "gen Question",
    genAnswer: "genAnswer",
    intKnowledge: "int Question",
    intAnswer: "intAnswer",
    advKnowledge: "adv Question",
    advAnswer: "intAnswer",
    enable: true
  },
  {
    key: '03',
    imagesrc: quiz2img,
    genKnowledge: "gen Question",
    genAnswer: "genAnswer",
    intKnowledge: "int Question",
    intAnswer: "intAnswer",
    advKnowledge: "adv Question",
    advAnswer: "intAnswer",
    enable: true
  },
  {
    key: '04',
    imagesrc: quiz2img,
    genKnowledge: "gen Question",
    genAnswer: "genAnswer",
    intKnowledge: "int Question",
    intAnswer: "intAnswer",
    advKnowledge: "adv Question",
    advAnswer: "intAnswer",
    enable: true
  },
  {
    key: '05',
    imagesrc: quiz2img,
    genKnowledge: "gen Question",
    genAnswer: "genAnswer",
    intKnowledge: "int Question",
    intAnswer: "intAnswer",
    advKnowledge: "adv Question",
    advAnswer: "intAnswer",
    enable: true
  },
  {
    key: '06',
    imagesrc: quiz2img,
    genKnowledge: "gen Question",
    genAnswer: "genAnswer",
    intKnowledge: "int Question",
    intAnswer: "intAnswer",
    advKnowledge: "adv Question",
    advAnswer: "intAnswer",
    enable: true
  },
  {
    key: '07',
    imagesrc: quiz2img,
    genKnowledge: "gen Question",
    genAnswer: "genAnswer",
    intKnowledge: "int Question",
    intAnswer: "intAnswer",
    advKnowledge: "adv Question",
    advAnswer: "intAnswer",
    enable: true
  },
  {
    key: '08',
    imagesrc: quiz2img,
    genKnowledge: "gen Question",
    genAnswer: "genAnswer",
    intKnowledge: "int Question",
    intAnswer: "intAnswer",
    advKnowledge: "adv Question",
    advAnswer: "intAnswer",
    enable: true
  },
  {
    key: '09',
    imagesrc: quiz2img,
    genKnowledge: "gen Question",
    genAnswer: "genAnswer",
    intKnowledge: "int Question",
    intAnswer: "intAnswer",
    advKnowledge: "adv Question",
    advAnswer: "intAnswer",
    enable: true
  },
  {
    key: '10',
    imagesrc: quiz2img,
    genKnowledge: "gen Question",
    genAnswer: "genAnswer",
    intKnowledge: "int Question",
    intAnswer: "intAnswer",
    advKnowledge: "adv Question",
    advAnswer: "intAnswer",
    enable: true
  },
  {
    key: '11',
    imagesrc: quiz2img,
    genKnowledge: "gen Question",
    genAnswer: "genAnswer",
    intKnowledge: "int Question",
    intAnswer: "intAnswer",
    advKnowledge: "adv Question",
    advAnswer: "intAnswer",
    enable: true
  },
  {
    key: '12',
    imagesrc: quiz2img,
    genKnowledge: "gen Question",
    genAnswer: "genAnswer",
    intKnowledge: "int Question",
    intAnswer: "intAnswer",
    advKnowledge: "adv Question",
    advAnswer: "intAnswer",
    enable: true
  },
  {
    key: '13',
    imagesrc: quiz2img,
    genKnowledge: "gen Question",
    genAnswer: "genAnswer",
    intKnowledge: "int Question",
    intAnswer: "intAnswer",
    advKnowledge: "adv Question",
    advAnswer: "intAnswer",
    enable: true
  },
  {
    key: '14',
    imagesrc: quiz2img,
    genKnowledge: "gen Question",
    genAnswer: "genAnswer",
    intKnowledge: "int Question",
    intAnswer: "intAnswer",
    advKnowledge: "adv Question",
    advAnswer: "intAnswer",
    enable: true
  },
  {
    key: '15',
    imagesrc: quiz2img,
    genKnowledge: "gen Question",
    genAnswer: "genAnswer",
    intKnowledge: "int Question",
    intAnswer: "intAnswer",
    advKnowledge: "adv Question",
    advAnswer: "intAnswer",
    enable: true
  },
  {
    key: '16',
    imagesrc: quiz2img,
    genKnowledge: "gen Question",
    genAnswer: "genAnswer",
    intKnowledge: "int Question",
    intAnswer: "intAnswer",
    advKnowledge: "adv Question",
    advAnswer: "intAnswer",
    enable: true
  },
  {
    key: '17',
    imagesrc: quiz2img,
    genKnowledge: "gen Question",
    genAnswer: "genAnswer",
    intKnowledge: "int Question",
    intAnswer: "intAnswer",
    advKnowledge: "adv Question",
    advAnswer: "intAnswer",
    enable: true
  },
  {
    key: '18',
    imagesrc: quiz2img,
    genKnowledge: "gen Question",
    genAnswer: "genAnswer",
    intKnowledge: "int Question",
    intAnswer: "intAnswer",
    advKnowledge: "adv Question",
    advAnswer: "intAnswer",
    enable: true
  },
  {
    key: '19',
    imagesrc: quiz2img,
    genKnowledge: "gen Question",
    genAnswer: "genAnswer",
    intKnowledge: "int Question",
    intAnswer: "intAnswer",
    advKnowledge: "adv Question",
    advAnswer: "intAnswer",
    enable: true
  },
  {
    key: '20',
    imagesrc: quiz2img,
    genKnowledge: "gen Question",
    genAnswer: "genAnswer",
    intKnowledge: "int Question",
    intAnswer: "intAnswer",
    advKnowledge: "adv Question",
    advAnswer: "intAnswer",
    enable: true
  },
  {
    key: '21',
    imagesrc: quiz2img,
    genKnowledge: "gen Question",
    genAnswer: "genAnswer",
    intKnowledge: "int Question",
    intAnswer: "intAnswer",
    advKnowledge: "adv Question",
    advAnswer: "intAnswer",
    enable: true
  },
  {
    key: '22',
    imagesrc: quiz2img,
    genKnowledge: "gen Question",
    genAnswer: "genAnswer",
    intKnowledge: "int Question",
    intAnswer: "intAnswer",
    advKnowledge: "adv Question",
    advAnswer: "intAnswer",
    enable: true
  },
  {
    key: '23',
    imagesrc: quiz2img,
    genKnowledge: "gen Question",
    genAnswer: "genAnswer",
    intKnowledge: "int Question",
    intAnswer: "intAnswer",
    advKnowledge: "adv Question",
    advAnswer: "intAnswer",
    enable: true
  },
  {
    key: '24',
    imagesrc: quiz2img,
    genKnowledge: "gen Question",
    genAnswer: "genAnswer",
    intKnowledge: "int Question",
    intAnswer: "intAnswer",
    advKnowledge: "adv Question",
    advAnswer: "intAnswer",
    enable: true
  },
  {
    key: '25',
    imagesrc: quiz2img,
    genKnowledge: "gen Question",
    genAnswer: "genAnswer",
    intKnowledge: "int Question",
    intAnswer: "intAnswer",
    advKnowledge: "adv Question",
    advAnswer: "intAnswer",
    enable: true
  },
  {
    key: '26',
    imagesrc: quiz2img,
    genKnowledge: "gen Question",
    genAnswer: "genAnswer",
    intKnowledge: "int Question",
    intAnswer: "intAnswer",
    advKnowledge: "adv Question",
    advAnswer: "intAnswer",
    enable: true
  },
  {
    key: '27',
    imagesrc: quiz2img,
    genKnowledge: "gen Question",
    genAnswer: "genAnswer",
    intKnowledge: "int Question",
    intAnswer: "intAnswer",
    advKnowledge: "adv Question",
    advAnswer: "intAnswer",
    enable: true
  },
  {
    key: '28',
    imagesrc: quiz2img,
    genKnowledge: "gen Question",
    genAnswer: "genAnswer",
    intKnowledge: "int Question",
    intAnswer: "intAnswer",
    advKnowledge: "adv Question",
    advAnswer: "intAnswer",
    enable: true
  },
  {
    key: '29',
    imagesrc: quiz2img,
    genKnowledge: "gen Question",
    genAnswer: "genAnswer",
    intKnowledge: "int Question",
    intAnswer: "intAnswer",
    advKnowledge: "adv Question",
    advAnswer: "intAnswer",
    enable: true
  },
  {
    key: '30',
    imagesrc: quiz2img,
    genKnowledge: "gen Question",
    genAnswer: "genAnswer",
    intKnowledge: "int Question",
    intAnswer: "intAnswer",
    advKnowledge: "adv Question",
    advAnswer: "intAnswer",
    enable: true
  },
  {
    key: '31',
    imagesrc: quiz2img,
    genKnowledge: "gen Question",
    genAnswer: "genAnswer",
    intKnowledge: "int Question",
    intAnswer: "intAnswer",
    advKnowledge: "adv Question",
    advAnswer: "intAnswer",
    enable: true
  },
  {
    key: '32',
    imagesrc: quiz2img,
    genKnowledge: "gen Question",
    genAnswer: "genAnswer",
    intKnowledge: "int Question",
    intAnswer: "intAnswer",
    advKnowledge: "adv Question",
    advAnswer: "intAnswer",
    enable: true
  },
  {
    key: '33',
    imagesrc: quiz2img,
    genKnowledge: "gen Question",
    genAnswer: "genAnswer",
    intKnowledge: "int Question",
    intAnswer: "intAnswer",
    advKnowledge: "adv Question",
    advAnswer: "intAnswer",
    enable: true
  },
  {
    key: '34',
    imagesrc: quiz2img,
    genKnowledge: "gen Question",
    genAnswer: "genAnswer",
    intKnowledge: "int Question",
    intAnswer: "intAnswer",
    advKnowledge: "adv Question",
    advAnswer: "intAnswer",
    enable: true
  },
  {
    key: '35',
    imagesrc: quiz2img,
    genKnowledge: "gen Question",
    genAnswer: "genAnswer",
    intKnowledge: "int Question",
    intAnswer: "intAnswer",
    advKnowledge: "adv Question",
    advAnswer: "intAnswer",
    enable: true
  },
  {
    key: '36',
    imagesrc: quiz2img,
    genKnowledge: "gen Question",
    genAnswer: "genAnswer",
    intKnowledge: "int Question",
    intAnswer: "intAnswer",
    advKnowledge: "adv Question",
    advAnswer: "intAnswer",
    enable: true
  },
  {
    key: '37',
    imagesrc: quiz2img,
    genKnowledge: "gen Question",
    genAnswer: "genAnswer",
    intKnowledge: "int Question",
    intAnswer: "intAnswer",
    advKnowledge: "adv Question",
    advAnswer: "intAnswer",
    enable: true
  },
  {
    key: '38',
    imagesrc: quiz2img,
    genKnowledge: "gen Question",
    genAnswer: "genAnswer",
    intKnowledge: "int Question",
    intAnswer: "intAnswer",
    advKnowledge: "adv Question",
    advAnswer: "intAnswer",
    enable: true
  },
  {
    key: '39',
    imagesrc: quiz2img,
    genKnowledge: "gen Question",
    genAnswer: "genAnswer",
    intKnowledge: "int Question",
    intAnswer: "intAnswer",
    advKnowledge: "adv Question",
    advAnswer: "intAnswer",
    enable: false
  },
  {
    key: '40',
    imagesrc: quiz2img,
    genKnowledge: "gen Question",
    genAnswer: "genAnswer",
    intKnowledge: "int Question",
    intAnswer: "intAnswer",
    advKnowledge: "adv Question",
    advAnswer: "intAnswer",
    enable: true
  },
]
